name: merger
description: "Library for merging Maps and Lists with different merging strategies"
version: 1.0.0
homepage: https://github.com/alphamikle/merger

environment:
  sdk: ">=3.0.0 <4.0.0"

dev_dependencies:
  test: ^1.25.8
  nanc_lints: ^1.0.0

flutter: